# Generated by Django 4.2.7 on 2023-12-13 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypc',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
